CREATE TABLE [dbo].[CIS_UserAccount]
(
	[UserAccountID] UNIQUEIDENTIFIER NOT NULL DEFAULT(newid()) PRIMARY KEY  ,
	[SID] UNIQUEIDENTIFIER NOT NULL,
	[Username] NVARCHAR(300) NOT NULL,
	[Password] NVARCHAR(300) NOT NULL,
	[Active] BIT NOT NULL DEFAULT(1), 
    [CreateDate] DATETIME NOT NULL DEFAULT GETDATE(), 
    [Status] INT NOT NULL DEFAULT 1, 



)
